
sandpit: # env name
  db_config:
    db_name: ocean_studio_III
    replica_set: rs_falcon
    hosts:
      - host: d-rh7-2
        port: 27017
    username: mongodb_admin
    password: mongodb
    auth_source: admin
    auth_mechanism: SCRAM-SHA-256
    use_ssl: False
    ssl_certificate_file: ""
    ssl_ca_file: ""
